#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flex
Version  : 2.6.0
Release  : 15
URL      : http://downloads.sourceforge.net/flex/flex-2.6.0.tar.bz2
Source0  : http://downloads.sourceforge.net/flex/flex-2.6.0.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.0+
Requires: flex-bin
Requires: flex-lib
Requires: flex-doc
Requires: flex-locales
BuildRequires : bison
BuildRequires : flex

%description
This is flex, the fast lexical analyzer generator.
flex is a tool for generating scanners: programs which recognize
lexical patterns in text.

%package bin
Summary: bin components for the flex package.
Group: Binaries

%description bin
bin components for the flex package.


%package dev
Summary: dev components for the flex package.
Group: Development
Requires: flex-lib
Requires: flex-bin
Provides: flex-devel

%description dev
dev components for the flex package.


%package doc
Summary: doc components for the flex package.
Group: Documentation

%description doc
doc components for the flex package.


%package lib
Summary: lib components for the flex package.
Group: Libraries

%description lib
lib components for the flex package.


%package locales
Summary: locales components for the flex package.
Group: Default

%description locales
locales components for the flex package.


%prep
%setup -q -n flex-2.6.0

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang flex

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/flex
/usr/bin/flex++

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/flex/*
%doc /usr/share/info/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f flex.lang 
%defattr(-,root,root,-)

